# Generated by Django 2.0.2 on 2018-04-22 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180422_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='my_status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 22, 8, 17, 52, 528515)),
        ),
    ]
